APP_NAME="NetForge"
DNS_SERVERS="1.1.1.1 1.0.0.1 8.8.8.8"
DNS_OVER_TLS="yes"
ETHERNET_METRIC=100
WIFI_METRIC_ALONE=600
WIFI_METRIC_WITH_ETH=700
DISABLE_SSHD=true
DISABLE_FILE_SHARE=true
HIGH_PERFORMANCE_POWER=false
RESPECT_VPN=true
CAPTIVE_PORTAL_DNS="1.1.1.1 8.8.8.8"
CAPTIVE_AUTO_RESTORE_SECONDS=600
